create table song (song_pk  serial not null, song_id int4, song_name varchar(255), primary key (song_pk));
create table users (user_id  serial not null, email varchar(255), password varchar(255), username varchar(255), primary key (user_id));
create table users_songs (user_id int4 not null, song_pk int4 not null, primary key (user_id, song_pk));
alter table if exists song add constraint UK_cmv5wgqu5b8hl5wnblm1b5kx6 unique (song_id);
alter table if exists users add constraint UK_r43af9ap4edm43mmtq01oddj6 unique (username);
alter table if exists users_songs add constraint FKe8x5j9fpxsisexui2vm9lnrgl foreign key (song_pk) references song;
alter table if exists users_songs add constraint FK7jxoobydr84yuyj84n7161pre foreign key (user_id) references users;
create table song (song_pk  serial not null, song_id int4, song_name varchar(255), primary key (song_pk));
create table users (user_id  serial not null, email varchar(255), password varchar(255), username varchar(255), primary key (user_id));
create table users_songs (user_id int4 not null, song_pk int4 not null, primary key (user_id, song_pk));
alter table if exists song add constraint UK_cmv5wgqu5b8hl5wnblm1b5kx6 unique (song_id);
alter table if exists users add constraint UK_r43af9ap4edm43mmtq01oddj6 unique (username);
alter table if exists users_songs add constraint FKe8x5j9fpxsisexui2vm9lnrgl foreign key (song_pk) references song;
alter table if exists users_songs add constraint FK7jxoobydr84yuyj84n7161pre foreign key (user_id) references users;
create table song (song_pk  serial not null, song_id int4, song_name varchar(255), primary key (song_pk));
create table users (user_id  serial not null, email varchar(255), password varchar(255), username varchar(255), primary key (user_id));
create table users_songs (user_id int4 not null, song_pk int4 not null, primary key (user_id, song_pk));
alter table if exists song add constraint UK_cmv5wgqu5b8hl5wnblm1b5kx6 unique (song_id);
alter table if exists users add constraint UK_r43af9ap4edm43mmtq01oddj6 unique (username);
alter table if exists users_songs add constraint FKe8x5j9fpxsisexui2vm9lnrgl foreign key (song_pk) references song;
alter table if exists users_songs add constraint FK7jxoobydr84yuyj84n7161pre foreign key (user_id) references users;
create table song (song_pk  serial not null, song_id int4, song_name varchar(255), primary key (song_pk));
create table users (user_id  serial not null, email varchar(255), password varchar(255), username varchar(255), primary key (user_id));
create table users_songs (user_id int4 not null, song_pk int4 not null, primary key (user_id, song_pk));
alter table if exists song add constraint UK_cmv5wgqu5b8hl5wnblm1b5kx6 unique (song_id);
alter table if exists users add constraint UK_r43af9ap4edm43mmtq01oddj6 unique (username);
alter table if exists users_songs add constraint FKe8x5j9fpxsisexui2vm9lnrgl foreign key (song_pk) references song;
alter table if exists users_songs add constraint FK7jxoobydr84yuyj84n7161pre foreign key (user_id) references users;
